// src/components/ProjectDialog.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch } from 'vue'
import { competencies } from '../data/competencies'
import type { Project } from '../types'

const props = defineProps<{ project: Project | null }>()
const emit = defineEmits<{ close: [] }>()
const dialog = ref<HTMLDialogElement | null>(null)

const associatedCompetencies = computed(() =>
  competencies.filter((competency) => props.project?.competencyIds.includes(competency.id)),
)

watch(
  () => props.project,
  async (project) => {
    await nextTick()
    if (project && dialog.value && !dialog.value.open) dialog.value.showModal()
  },
)

function closeDialog(): void {
  dialog.value?.close()
}

function handleClose(): void {
  const projectId = props.project?.id
  emit('close')
  if (projectId) {
    requestAnimationFrame(() => {
      document.querySelector<HTMLElement>(`[data-project-trigger="${projectId}"]`)?.focus()
    })
  }
}
</script>

<template>
  <dialog
    ref="dialog"
    class="project-dialog"
    aria-labelledby="project-dialog-title"
    @close="handleClose"
  >
    <article
      v-if="project"
      class="dialog-content"
    >
      <header class="dialog-header">
        <div>
          <p class="eyebrow">
            {{ project.origin }} · {{ project.period }}
          </p>
          <h2 id="project-dialog-title">
            {{ project.title }}
          </h2>
          <p class="dialog-summary">
            {{ project.summary }}
          </p>
        </div>
        <button
          class="icon-button"
          type="button"
          aria-label="Fermer la fiche du projet"
          @click="closeDialog"
        >
          ×
        </button>
      </header>

      <div class="dialog-grid">
        <section v-if="project.details?.context">
          <h3>Contexte</h3>
          <p>{{ project.details.context }}</p>
        </section>
        <section v-if="project.details?.objective">
          <h3>Objectif</h3>
          <p>{{ project.details.objective }}</p>
        </section>
        <section v-if="project.details?.need">
          <h3>Besoin traité</h3>
          <p>{{ project.details.need }}</p>
        </section>
        <section v-if="project.details?.work?.length">
          <h3>Travail réalisé</h3>
          <ul>
            <li
              v-for="item in project.details.work"
              :key="item"
            >
              {{ item }}
            </li>
          </ul>
        </section>
        <section v-if="project.details?.contribution?.length">
          <h3>Contribution personnelle</h3>
          <ul>
            <li
              v-for="item in project.details.contribution"
              :key="item"
            >
              {{ item }}
            </li>
          </ul>
        </section>
        <section v-if="project.details?.methods?.length">
          <h3>Méthodes et outils</h3>
          <ul>
            <li
              v-for="item in project.details.methods"
              :key="item"
            >
              {{ item }}
            </li>
          </ul>
        </section>
        <section v-if="project.details?.constraints?.length">
          <h3>Contraintes</h3>
          <ul>
            <li
              v-for="item in project.details.constraints"
              :key="item"
            >
              {{ item }}
            </li>
          </ul>
        </section>
        <section v-if="project.details?.result">
          <h3>Résultat</h3>
          <p>{{ project.details.result }}</p>
        </section>
        <section v-if="project.details?.lessons?.length">
          <h3>Retour d’expérience</h3>
          <ul>
            <li
              v-for="item in project.details.lessons"
              :key="item"
            >
              {{ item }}
            </li>
          </ul>
        </section>
      </div>

      <section class="dialog-section">
        <h3>Technologies</h3>
        <ul class="tag-list">
          <li
            v-for="technology in project.technologies"
            :key="technology"
          >
            {{ technology }}
          </li>
        </ul>
      </section>

      <section class="dialog-section">
        <h3>Compétences E5 associées</h3>
        <ul
          v-if="associatedCompetencies.length"
          class="competency-links"
        >
          <li
            v-for="competency in associatedCompetencies"
            :key="competency.id"
          >
            <a
              :href="`#competence-${competency.id.replace('.', '-')}`"
              @click="closeDialog"
            >
              {{ competency.id }} — {{ competency.title }}
            </a>
          </li>
        </ul>
        <p
          v-else
          class="empty-inline"
        >
          Aucune association E5 n’a encore été validée pour cette réalisation.
        </p>
      </section>

      <section
        v-if="!project.media?.length && project.id === 'distributeur-couverts'"
        class="media-placeholder"
      >
        <h3>Galerie</h3>
        <p>Les captures autorisées pourront être ajoutées ici après sélection des fichiers à publier.</p>
      </section>

      <footer class="dialog-actions">
        <a
          v-for="link in project.links"
          :key="link.url"
          class="button button-secondary"
          :href="link.url"
          target="_blank"
          rel="noopener noreferrer"
        >
          {{ link.label }} <span aria-hidden="true">↗</span>
        </a>
        <button
          class="button button-primary"
          type="button"
          @click="closeDialog"
        >
          Fermer
        </button>
      </footer>
    </article>
  </dialog>
</template>

// src/lib/components/ProjectDialog.svelte
<script lang="ts">
  import { competencies } from '$lib/data/competencies'
  import type { Project } from '$lib/types'

  interface Props {
    project: Project | null
    onClose: () => void
  }

  let { project, onClose }: Props = $props()
  let dialog: HTMLDialogElement | undefined

  const associatedCompetencies = $derived(
    competencies.filter((competency) => project?.competencyIds.includes(competency.id)),
  )

  $effect(() => {
    if (project && dialog && !dialog.open) dialog.showModal()
  })

  function closeDialog(): void {
    dialog?.close()
  }
</script>

<dialog bind:this={dialog} class="project-dialog" aria-labelledby="project-dialog-title" onclose={onClose}>
  {#if project}
    <article class="dialog-content">
      <header class="dialog-header">
        <div>
          <p class="eyebrow">{project.origin} · {project.period}</p>
          <h2 id="project-dialog-title">{project.title}</h2>
          <p class="dialog-summary">{project.summary}</p>
        </div>
        <button
          class="icon-button"
          type="button"
          aria-label="Fermer la fiche du projet"
          onclick={closeDialog}
        >
          ×
        </button>
      </header>

      <div class="dialog-grid">
        {#if project.details?.context}
          <section>
            <h3>Contexte</h3>
            <p>{project.details.context}</p>
          </section>
        {/if}
        {#if project.details?.objective}
          <section>
            <h3>Objectif</h3>
            <p>{project.details.objective}</p>
          </section>
        {/if}
        {#if project.details?.need}
          <section>
            <h3>Besoin traité</h3>
            <p>{project.details.need}</p>
          </section>
        {/if}
        {#if project.details?.work?.length}
          <section>
            <h3>Travail réalisé</h3>
            <ul>
              {#each project.details.work as item (item)}
                <li>{item}</li>
              {/each}
            </ul>
          </section>
        {/if}
        {#if project.details?.contribution?.length}
          <section>
            <h3>Contribution personnelle</h3>
            <ul>
              {#each project.details.contribution as item (item)}
                <li>{item}</li>
              {/each}
            </ul>
          </section>
        {/if}
        {#if project.details?.methods?.length}
          <section>
            <h3>Méthodes et outils</h3>
            <ul>
              {#each project.details.methods as item (item)}
                <li>{item}</li>
              {/each}
            </ul>
          </section>
        {/if}
        {#if project.details?.constraints?.length}
          <section>
            <h3>Contraintes</h3>
            <ul>
              {#each project.details.constraints as item (item)}
                <li>{item}</li>
              {/each}
            </ul>
          </section>
        {/if}
        {#if project.details?.result}
          <section>
            <h3>Résultat</h3>
            <p>{project.details.result}</p>
          </section>
        {/if}
        {#if project.details?.lessons?.length}
          <section>
            <h3>Retour d’expérience</h3>
            <ul>
              {#each project.details.lessons as item (item)}
                <li>{item}</li>
              {/each}
            </ul>
          </section>
        {/if}
      </div>

      <section class="dialog-section">
        <h3>Technologies</h3>
        <ul class="tag-list">
          {#each project.technologies as technology (technology)}
            <li>{technology}</li>
          {/each}
        </ul>
      </section>

      <section class="dialog-section">
        <h3>Compétences E5 associées</h3>
        {#if associatedCompetencies.length}
          <ul class="competency-links">
            {#each associatedCompetencies as competency (competency.id)}
              <li>
                <a href={`#competence-${competency.id.replace('.', '-')}`} onclick={closeDialog}>
                  {competency.id} — {competency.title}
                </a>
              </li>
            {/each}
          </ul>
        {:else}
          <p class="empty-inline">Aucune association E5 n’a encore été validée pour cette réalisation.</p>
        {/if}
      </section>

      {#if !project.media?.length && project.id === 'distributeur-couverts'}
        <section class="media-placeholder">
          <h3>Galerie</h3>
          <p>Les captures autorisées pourront être ajoutées ici après sélection des fichiers à publier.</p>
        </section>
      {/if}

      <footer class="dialog-actions">
        {#each project.links as link (link.url)}
          <a
            class="button button-secondary"
            href={link.url}
            target="_blank"
            rel="external noopener noreferrer"
          >
            {link.label} <span aria-hidden="true">↗</span>
          </a>
        {/each}
        <button class="button button-primary" type="button" onclick={closeDialog}>Fermer</button>
      </footer>
    </article>
  {/if}
</dialog>
